#!/bin/bash
# auto-complete
if [ -f $(brew --prefix)/etc/bash_completion ]; then
  . $(brew --prefix)/etc/bash_completion
fi

# rvm
[[ -r $rvm_path/scripts/completion ]] && . $rvm_path/scripts/completion

# kubernetes
source <(kubectl completion bash)

# direnv
# eval "$(direnv hook bash)"

# istio
[[ -r ~/tools/istio/tools/istioctl.bash ]] && source ~/tools/istio/tools/istioctl.bash

# gcloud
if [ -f '/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/completion.bash.inc' ]; then . '/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/completion.bash.inc'; fi
